name: "CI"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    env:
      MAINLINE: refs/heads/master
      DOCKERTAG: latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v13
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      # This also runs nix-build.
      - uses: cachix/cachix-action@v8
        with:
          name: srid
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
          # Only needed for private caches
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      # This downloads deps from Nix cache, builds neuron, as well as run tests
      - name: Build 🔧
        run: |
          nix-build -j4 --no-out-link ci.nix
          # Test default.nix
          nix-build -j4
          # Test flake.nix
          nix build --out-link flake-result
      - name: Verify output of default.nix & flake.nix
        run: |
          [ $(readlink result) = $(readlink flake-result) ]
      - name: Retrieve neuron version
        run: |
          echo "NEURONVER=$(./result/bin/neuron --version)" >> $GITHUB_ENV
      - name: Publish Docker image to Docker Hub
        if: ${{ github.ref == env.MAINLINE && runner.os == 'Linux' }}
        run: |
          docker load -i $(nix-build docker.nix --argstr tag "${{ env.DOCKERTAG }}")
          docker tag "sridca/neuron:${{ env.DOCKERTAG }}" "sridca/neuron:${{env.NEURONVER}}"
          echo ${{ secrets.DOCKER_PASS }} | docker login -u sridca --password-stdin
          set -x
          docker push "sridca/neuron:${{ env.DOCKERTAG }}"
          docker push "sridca/neuron:${{ env.NEURONVER }}"
      # macOS is not supported: https://github.com/matthewbauer/nix-bundle/issues/17
      - name: Bundle up
        if: ${{ github.ref == env.MAINLINE && runner.os == 'Linux' }}
        run: |
          git clone -b neuron-stable https://github.com/srid/nix-bundle.git tmp/nix-bundle
          cd tmp/nix-bundle
          NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs/tarball/ab5863afada3c1b50fc43bf774b75ea71b287cde ./nix-bundle.sh '(import ../.. {})' /bin/neuron > ../../neuron-linux-bundle
          cd -
          mkdir ~/bundle
          cp neuron-linux-bundle ~/bundle/neuron
          chmod a+x neuron-linux-bundle ~/bundle/neuron
      - name: Upload bundle as artifact
        uses: actions/upload-artifact@v2
        if: ${{ github.ref == env.MAINLINE && runner.os == 'Linux' }}
        with:
          name: neuron-bundle-linux
          path: ~/bundle/neuron
